version: '3.8'
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./anonymous-server-backend
    env_file:
      - ./anonymous-server-backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./anonymous-frontend
    environment:
      NEXT_PUBLIC_LOGIN_URL: http://backend:8080/login
      NEXT_PUBLIC_WEBSOCKET_URL: ws://backend:8080
      NEXT_PUBLIC_LOGOUT_URL: http://backend:8080/logout
    ports:
      - "3000:3000"
    depends_on:
      - backend

  python-service:
    build:
      context: ./finance-microservice
    ports:
      - "5005:5005"
    depends_on:
      - mongo

volumes:
  mongo-data:
