# Build Stage
FROM zelshahawy/alpine-golang-buildimage:1.13 AS build-stage

LABEL app="build-Anonymous_backend"
LABEL REPO="https://github.com/zelshahawy/Anonymous_backend"

ENV PROJPATH=/go/src/github.com/zelshahawy/Anonymous_backend

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

ADD . /go/src/github.com/zelshahawy/Anonymous_backend
WORKDIR /go/src/github.com/zelshahawy/Anonymous_backend

RUN make build-alpine

# Final Stage
FROM zelshahawy/alpine-base-image:latest

ARG GIT_COMMIT
ARG VERSION
LABEL REPO="https://github.com/zelshahawy/Anonymous_backend"
LABEL GIT_COMMIT=$GIT_COMMIT
LABEL VERSION=$VERSION

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:/opt/Anonymous_backend/bin

WORKDIR /opt/Anonymous_backend/bin

COPY --from=build-stage /go/src/github.com/zelshahawy/Anonymous_backend/bin/Anonymous_backend /opt/Anonymous_backend/bin/
RUN chmod +x /opt/Anonymous_backend/bin/Anonymous_backend

EXPOSE 8081

# Create appuser
RUN adduser -D -g '' Anonymous_backend
USER Anonymous_backend

ENTRYPOINT ["/usr/bin/dumb-init", "--"]

CMD ["/opt/Anonymous_backend/bin/Anonymous_backend"]
